### ISSUE TITLE
NoSuchFieldError: UPPER_CAMEL_CASE error when using Postmark Java SDK

### ISSUE THREAD

**Issue by incube8r** [wildbit/postmark-java#15]
What is the UPPER_CAMEL_CASE error in this context?

```
Caused by: java.lang.NoSuchFieldError: UPPER_CAMEL_CASE
    at com.wildbit.java.postmark.client.data.DataHandler.<init>(DataHandler.java:20)
    at com.wildbit.java.postmark.client.data.DataHandler.<init>(DataHandler.java:25)
    at com.wildbit.java.postmark.client.HttpClientHandler.<init>(HttpClientHandler.java:22)
    at com.wildbit.java.postmark.client.BaseApiClient.<init>(BaseApiClient.java:18)
    at com.wildbit.java.postmark.client.ApiClient.<init>(ApiClient.java:43)
    at com.wildbit.java.postmark.Postmark.getApiClient(Postmark.java:62)
```
I already have the dependencies:

```
    <dependency>
        <groupId>com.fasterxml.jackson.datatype</groupId>
        <artifactId>jackson-datatype-jdk8</artifactId>
        <version>2.10.0</version>
    </dependency>
    <dependency>
        <groupId>com.wildbit.java</groupId>
        <artifactId>postmark</artifactId>
        <version>1.2.1</version>
        <exclusions>
            <exclusion>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-log4j12</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
```

I checked and found that the issue is related to jackson-datatype however adding it does not exactly fix the error.

**Comment by ibalosh** [comment]
Hi @incube8r 

I will need bit more details to identify where the error happens with the parser. Could you share details for which call do you get this error?
