### ISSUE TITLE
[1.5.6] ProcessingException after upgrading from 1.5.5 to 1.5.6 

### ISSUE THREAD

**Issue by almothafar** [wildbit/postmark-java#24]
I just did an update for my dependency of this library from 1.5.5 to 1.5.6 and this issue happened, reverting back to 1.5.5 solved the issue

```

[debug] - [                    ] - a.s.UserAlertsMaintenanceService - javax.ws.rs.ProcessingException: javax.ws.rs.ProcessingException
java.util.concurrent.CompletionException: javax.ws.rs.ProcessingException: javax.ws.rs.ProcessingException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:1186)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1208)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
Caused by: javax.ws.rs.ProcessingException: javax.ws.rs.ProcessingException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
Caused by: javax.ws.rs.ProcessingException: null
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:287)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:428)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:324)
	at com.wildbit.java.postmark.client.HttpClient.execute(HttpClient.java:66)
Caused by: java.lang.NullPointerException: null
	at java.base/java.util.LinkedList$ListItr.next(LinkedList.java:897)
	at org.glassfish.jersey.internal.util.collection.Views$1$1.next(Views.java:96)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.setOutboundHeaders(HttpUrlConnector.java:428)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:387)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:282)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:278)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
[error] - [                    ] - a.d.TaskInvocation - null
javax.ws.rs.ProcessingException: null
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:287)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:428)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:324)
	at com.wildbit.java.postmark.client.HttpClient.execute(HttpClient.java:66)
Caused by: java.lang.NullPointerException: null
	at java.base/java.util.LinkedList$ListItr.next(LinkedList.java:897)
	at org.glassfish.jersey.internal.util.collection.Views$1$1.next(Views.java:96)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.setOutboundHeaders(HttpUrlConnector.java:428)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:387)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:282)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:278)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229)


```

**Comment by ibalosh** [comment]
Hi @almothafar 

could you share more details where do you see this error when you update the dependency?  
Did you update along the way anything else?

The reason why I am mentioning this is since the update is very small, it just adds additional methods to be able to use custom URL for [server and account api clients.](https://github.com/wildbit/postmark-java/commit/7219a9eac613e22ba9791a220f3103636edad205)

**Comment by almothafar** [comment]
Actually, it was a runtime error,, it is just simply sending an email code that I'm using changed nothing but it failed to send.

Just an example code for what I'm using not real one:

```java
private final ApiClient client = Postmark.getApiClient(configuration.getString("mailer.user"));
final TemplatedMessage templatedMessage = new TemplatedMessage("example@domain.com", "to@email.com", TEMPLATE_ID);
client.deliverMessageWithTemplate(templatedMessage);
```

I was able to see the issue in the development environment.

**Comment by ibalosh** [comment]
I see, could you try to initialise client by doing the basic:

```
ApiClient client = Postmark.getApiClient("api-token-id-xxxx-xxxxx");
```

where you would use your server token. Also, could you share the full runtime error you got, and the Java version you used.
We tried this locally with java 8 and haven't noticed any issues.

**Comment by almothafar** [comment]
Ok, `Postmark.getApiClient(configuration.getString("mailer.user"))` is working fine in 1.5.5 and I checked that `configuration.getString("mailer.user")` returns with a correct value, it seems the value sent correctly.

On the second note, I'm using a Play Framework project, with JDK 11.

Finally, I posted the full stack trace already in the OP, nothing else above or below.

**Comment by ibalosh** [comment]
I see, could you try though the initialisation the way I posted above with version 1.5.6? 
The only change in the version is related to init, which has one more parameter optional now.

Unfortunately in the exception you posted (which is coming from the Jersey client which was not updated) we can't see enough details to be able to reproduce the issue.

**Comment by almothafar** [comment]
It seems the issue was with stuck compiled classes, I cleared out the `target` folder these selected ones in sbt project:
![image](https://user-images.githubusercontent.com/13887564/109645573-b7c23600-7b5f-11eb-96c9-92398519b63a.png)

And now it is working fine.

**Comment by ibalosh** [comment]
Hey @almothafar 

Ah I see, glad it works now! If you see any issues while using the library along the way, let us know

Igor

**Comment by almothafar** [comment]
@ibalosh  I still see this issue even in production, it seems so random, I can't really give a scenario of it, even with the fresh build I still get that issue sometimes, I just do restart and it works, that system was running for a long time without any issues these issues start to happen since 1.5.6

**Comment by ibalosh** [comment]
hey @almothafar 

unfortunately we don't have enough details from the exception and reproduction details above to reproduce the issue and check it more. We are confident though that it is not related to the version update, since the update from 1.5.5 to 1.5.6 is [minimal](https://github.com/wildbit/postmark-java/commit/7219a9eac613e22ba9791a220f3103636edad205) and is related only to allowing customers to use a custom test API urls if they want. Also we haven't seen any other reports related to this issue.

What I would check though how is if you are running the calls in parallel and how these affect your network connection.
You can experiment with timeouts too for http client and see if it helps:

```
ApiClient client = Postmark.getApiClient(token);
client.getHttpClient().setConnectTimeoutSeconds(300);
client.getHttpClient().setReadTimeoutSeconds(300);
```

and you could try debug mode for http client and see if you can get more detailed logs of the issue:

`client.setDebugMode();`

**Comment by almothafar** [comment]
The issue is still happening, it is so rare and so random, like one time every month or two, I can't really get a specific scenario how to reproduce the issue, the only solution that I do for now is just doing a restart.
