### ISSUE TITLE
HeaderValueException:Too many "Content-Type" header values: "[application/json, application/json]

### ISSUE THREAD

**Issue by enkuru** [wildbit/postmark-java#37]
Hi, seeing these errors time to time:
`org.glassfish.jersey.message.internal.HeaderValueException: Too many "Content-Type" header values: "[application/json]"
    at org.glassfish.jersey.message.internal.OutboundMessageContext.singleHeader(OutboundMessageContext.java:199)
    at org.glassfish.jersey.message.internal.OutboundMessageContext.getMediaType(OutboundMessageContext.java:270)
    at org.glassfish.jersey.client.ClientRequest.ensureMediaType(ClientRequest.java:511)
    at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:441)
    at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:369)
    at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:267)
    at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:297)
    at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:675)
    at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697)
    at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
    at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:691)
    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:674)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:450)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:351)
    at com.wildbit.java.postmark.client.HttpClient.execute(HttpClient.java:62)
    at com.wildbit.java.postmark.client.HttpClientHandler.execute(HttpClientHandler.java:62)
    at com.wildbit.java.postmark.client.ApiClient.deliverMessageWithTemplate(ApiClient.java:167)
    at io.wamo.clients.mail.provider.PostmarkClient.sendWithTemplateId(PostmarkClient.java:56)`

`java.lang.NullPointerException: null
    at java.util.LinkedList$ListItr.next(LinkedList.java:897)
    at java.util.AbstractCollection.toString(AbstractCollection.java:472)
    at org.glassfish.jersey.message.internal.OutboundMessageContext.singleHeader(OutboundMessageContext.java:199)
    at org.glassfish.jersey.message.internal.OutboundMessageContext.getMediaType(OutboundMessageContext.java:270)
    at org.glassfish.jersey.client.ClientRequest.ensureMediaType(ClientRequest.java:511)
    at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:441)
    at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:369)
    at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:267)
    at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:297)
    at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:675)
    at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697)
    at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
    at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:691)
    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:674)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:450)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:351)
    at com.wildbit.java.postmark.client.HttpClient.execute(HttpClient.java:62)
    at com.wildbit.java.postmark.client.HttpClientHandler.execute(HttpClientHandler.java:62)
    at com.wildbit.java.postmark.client.ApiClient.deliverMessageWithTemplate(ApiClient.java:167)
    at io.wamo.clients.mail.provider.PostmarkClient.sendWithTemplateId(PostmarkClient.java:56)`

we are using in safe thread with last version of the library which is 1.8.0

**Comment by ibalosh** [comment]
Hi @enkuru 

could you add any additional details to https://github.com/wildbit/postmark-java/issues/33 , it's easier to track the issue through single ticket.

If you can share any additional details there when you typically get this error that would be great!

**Comment by enkuru** [comment]
Hi @ibalosh I have added details

**Comment by Sheikh2Imran** [comment]
Hi @enkuru, did you solve your problem ?
