### ISSUE TITLE
com.fasterxml.jackson.databind.exc.InvalidFormatException

### ISSUE THREAD

**Issue by robmool** [wildbit/postmark-java#6]
Hi,

I get the following error message when sending a simple mail using the latest library.

Track trace:
 com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type java.util.Date from String "2018-04-13T14:50:37.4008047-04:00": not a valid representation (error: Failed to parse Date value '2018-04-13T14:50:37.4008047-04:00': Can not parse date "2018-04-13T14:50:37.4008047-0400": while it seems to fit format 'yyyy-MM-dd'T'HH:mm:ss.SSSZ', parsing fails (leniency? null))
 at [Source: {"To":"robm@dci.es","SubmittedAt":"2018-04-13T14:50:37.4008047-04:00","MessageID":"46f56d35-e169-4efa-a12d-160726177ae9","ErrorCode":0,"Message":"OK"}; line: 1, column: 35] (through reference chain: com.wildbit.java.postmark.client.data.model.message.MessageResponse["SubmittedAt"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:74)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1410)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:926)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseDate(StdDeserializer.java:819)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseDate(StdDeserializer.java:788)
	at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateBasedDeserializer._parseDate(DateDeserializers.java:172)
	at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer.deserialize(DateDeserializers.java:259)
	at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer.deserialize(DateDeserializers.java:242)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2858)
	at com.wildbit.java.postmark.client.data.DataHandler.fromJson(DataHandler.java:47)
	at com.wildbit.java.postmark.client.ApiClient.deliverMessage(ApiClient.java:56)

Any suggestions?

Thanks in advance,
Rob

**Comment by ibalosh** [comment]
Hi Rob

we noticed users receiving that one from time to time, due older version of Jackson library which handles parsing API responses. Updating library will resolve it.

They fixed it in version 2.9.2. It happens since Jackson does not parse "fractional" timezone correctly. Using up to date library should fix this issue.

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.2
