### ISSUE TITLE
Consider updating jersey to version 2.26+

### ISSUE THREAD

**Issue by wrey75** [wildbit/postmark-java#8]
Hello,

Here my code:
	TemplatedMessage message = new TemplatedMessage(from, "support@ddd.com");
	message.setTemplateId(6025382);
	Map<String,Object> model = new HashMap<>();
	model.put("firstName", "William");
	model.put("lastName", "uiop");
	model.put("action_url", "https://github.com/wildbit/postmark-java/issues/new?op=78");
	message.setTemplateModel(model);
	
	// send email with template
       MessageResponse response;
       response = client.deliverMessageWithTemplate(message);

and generates an unexpected error:

```
java.lang.IllegalStateException: InjectionManagerFactory not found.
	at org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:98)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:98)
	at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:68)
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:432)
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:341)
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:826)
	at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:285)
	at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:143)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:112)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:108)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:99)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:456)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:357)
	at com.wildbit.java.postmark.client.HttpClient.execute(HttpClient.java:61)
	at com.wildbit.java.postmark.client.HttpClientHandler.execute(HttpClientHandler.java:60)
	at com.wildbit.java.postmark.client.ApiClient.deliverMessageWithTemplate(ApiClient.java:157)
	at ...
 
```
I am running a website through Spring Boot 2 and the version 1.1 of the Postmark library.

Please, can you help?

**Comment by ibalosh** [comment]
Hu @wrey75 

hm, it seems that Spring boot 2 is using same library as our library for HTTP client requests - Jersey.
The problem arises from what I see, since we use older library version from Spring boot 2.

I will check posibility of updating library, but for now, could you try to resolve the issue by trying out the following options users used to solve Jersey request problem:

https://stackoverflow.com/questions/44088493/jersey-stopped-working-with-injectionmanagerfactory-not-found

from what I see users solved it by adding following dependency to pom.xml

```
<dependency>
        <groupId>org.glassfish.jersey.inject</groupId>
        <artifactId>jersey-hk2</artifactId>
    </dependency>
```

Let me know if that works?

**Comment by wrey75** [comment]
Hello,

Following your advice, I added the dependency below and works like a charm.

		<dependency>
			<groupId>org.glassfish.jersey.inject</groupId>
			<artifactId>jersey-hk2</artifactId>
			 <version>2.27</version>
		</dependency>

**Comment by ibalosh** [comment]
awesome! will add the solution to wiki pages

**Comment by snydergd** [comment]
So, what is happening is that Spring brings in a newer version than postmark uses, which externalizes some pieces to another dependency.  Adding that dependency fixes this issue, however, it looks like the newer (2.26 and up) versions [are not backwards compatible](https://eclipse-ee4j.github.io/jersey.github.io/release-notes/2.26.html).

Any chance this issue could be re-opened with the intent of updating the version used by Postmark?  Or does postmark not use the "reactive client API" portion provided in earlier versions, making this not a concern in itself?

Updating the version used by postmark would both resolve this problem, and prevent other potential problems/vulnerabilities from the older version being in Postmark.

**Comment by ibalosh** [comment]
Hey @snydergd ,

I will see review the library along with some other updates this week and see if we can bump the jersey version.

Igir

**Comment by ibalosh** [comment]
Hi @snydergd 

we have updated jersey version along one small update, in library version 1.5.0. We are using Jersey 2.27 from now on.

Igor

**Comment by ibalosh** [comment]
let us know if you will see any issue with new version

**Comment by snydergd** [comment]
Thanks!  I will keep you posted if we have any issues.
